// Assuming the prices provided are per hour, we convert them to per-minute rates.
const HOURLY_TO_MINUTE_RATE = (hourly: number) => hourly / 60;

export const PREDEFINED_CATEGORIES = [
    { id: 'cat-1', name: "Pantalones" },
    { id: 'cat-2', name: "Camisas" },
    { id: 'cat-3', name: "Vestidos" },
    { id: 'cat-4', name: "Faldas" },
    { id: 'cat-5', name: "Chaquetas" },
    { id: 'cat-6', name: "Cazadoras" },
    { id: 'cat-7', name: "Vestidos de novia, invitadas y damas de honor" },
    { id: 'cat-8', name: "Otros" },
];

export const PREDEFINED_SERVICES_CATEGORIZED = {
    "Pantalones": [
        { name: "Bajo de pantalón de vestir", rate: HOURLY_TO_MINUTE_RATE(14) },
        { name: "Bajo invisible a mano", rate: HOURLY_TO_MINUTE_RATE(14) },
        { name: "Pantalón de vestir con cinta", rate: HOURLY_TO_MINUTE_RATE(16) },
        { name: "Chándal de punto", rate: HOURLY_TO_MINUTE_RATE(10) },
        { name: "Ampliar o estrechar cintura", rate: HOURLY_TO_MINUTE_RATE(15) },
        { name: "Estrechar pierna", rate: HOURLY_TO_MINUTE_RATE(14) },
        { name: "Bajo de vaqueros", rate: HOURLY_TO_MINUTE_RATE(10) },
        { name: "Vaquero: estrechar cintura", rate: HOURLY_TO_MINUTE_RATE(15) },
        { name: "Vaquero: estrechar pierna", rate: HOURLY_TO_MINUTE_RATE(14) },
        { name: "Zurcir vaquero", rate: HOURLY_TO_MINUTE_RATE(8) },
        { name: "Estrechar lados (pantalón de campana)", rate: HOURLY_TO_MINUTE_RATE(12) },
        { name: "Cambiar bolsillos", rate: HOURLY_TO_MINUTE_RATE(14) },
        { name: "Abrir o cerrar abertura", rate: HOURLY_TO_MINUTE_RATE(10) },
        { name: "Cambiar goma", rate: HOURLY_TO_MINUTE_RATE(12) },
        { name: "Poner parche", rate: HOURLY_TO_MINUTE_RATE(8) },
        { name: "Coser roto", rate: HOURLY_TO_MINUTE_RATE(6) },
    ],
    "Camisas": [
        { name: "Cambiar cuello", rate: HOURLY_TO_MINUTE_RATE(12) },
        { name: "Voltear puños", rate: HOURLY_TO_MINUTE_RATE(12) },
        { name: "Acortar mangas", rate: HOURLY_TO_MINUTE_RATE(12) },
        { name: "Hacer bajo", rate: HOURLY_TO_MINUTE_RATE(10) },
        { name: "Hacer bajo con abertura", rate: HOURLY_TO_MINUTE_RATE(14) },
        { name: "Estrechar costados", rate: HOURLY_TO_MINUTE_RATE(12) },
        { name: "Ensanchar costados", rate: HOURLY_TO_MINUTE_RATE(12) },
        { name: "Estrechar hombros", rate: HOURLY_TO_MINUTE_RATE(14) },
        { name: "Estrechar lados", rate: HOURLY_TO_MINUTE_RATE(14) },
        { name: "Hacer abertura", rate: HOURLY_TO_MINUTE_RATE(8) },
    ],
    "Vestidos": [
        { name: "Bajo sencillo", rate: HOURLY_TO_MINUTE_RATE(12) },
        { name: "Bajo de punto a mano", rate: HOURLY_TO_MINUTE_RATE(14) },
        { name: "Cambiar cremallera", rate: HOURLY_TO_MINUTE_RATE(16) },
        { name: "Cremallera invisible", rate: HOURLY_TO_MINUTE_RATE(18) },
        { name: "Estrechar lados (sin forro)", rate: HOURLY_TO_MINUTE_RATE(12) },
        { name: "Estrechar lados (con forro)", rate: HOURLY_TO_MINUTE_RATE(16) },
        { name: "Subir tirantes", rate: HOURLY_TO_MINUTE_RATE(10) },
        { name: "Subir manga", rate: HOURLY_TO_MINUTE_RATE(12) },
        { name: "Subir hombros", rate: HOURLY_TO_MINUTE_RATE(14) },
        { name: "Poner botón (unidad)", rate: HOURLY_TO_MINUTE_RATE(4) },
        { name: "Abrir o cerrar abertura", rate: HOURLY_TO_MINUTE_RATE(6) },
        { name: "Adaptación premamá", rate: HOURLY_TO_MINUTE_RATE(14) },
    ],
    "Faldas": [
        { name: "Estrechar lados (sin forro)", rate: HOURLY_TO_MINUTE_RATE(12) },
        { name: "Estrechar lados (con forro)", rate: HOURLY_TO_MINUTE_RATE(16) },
        { name: "Cambiar cremallera", rate: HOURLY_TO_MINUTE_RATE(10) },
        { name: "Cambiar cremallera invisible", rate: HOURLY_TO_MINUTE_RATE(12) },
        { name: "Bajo a máquina", rate: HOURLY_TO_MINUTE_RATE(10) },
        { name: "Bajo a mano", rate: HOURLY_TO_MINUTE_RATE(12) },
        { name: "Bajo con forro a mano", rate: HOURLY_TO_MINUTE_RATE(16) },
    ],
    "Chaquetas": [
        { name: "Cortar mangas", rate: HOURLY_TO_MINUTE_RATE(16) },
        { name: "Cortar mangas (americana)", rate: HOURLY_TO_MINUTE_RATE(25) },
        { name: "Cerrar abertura", rate: HOURLY_TO_MINUTE_RATE(12) },
        { name: "Cortar bajo", rate: HOURLY_TO_MINUTE_RATE(14) },
        { name: "Cortar bajo (americana)", rate: HOURLY_TO_MINUTE_RATE(20) },
        { name: "Estrechar lados", rate: HOURLY_TO_MINUTE_RATE(16) },
    ],
    "Cazadoras": [
        { name: "Bajo sin abertura", rate: HOURLY_TO_MINUTE_RATE(12) },
        { name: "Bajo con abertura", rate: HOURLY_TO_MINUTE_RATE(12) },
        { name: "Estrechar lados", rate: HOURLY_TO_MINUTE_RATE(14) },
        { name: "Cremalleras hasta 40 cm", rate: HOURLY_TO_MINUTE_RATE(18) },
        { name: "Cambiar cremallera anorak (cremallera no incluida)", rate: HOURLY_TO_MINUTE_RATE(14) },
        { name: "Cambiar cremallera chándal (cremallera no incluida)", rate: HOURLY_TO_MINUTE_RATE(14) },
        { name: "Cambiar cremallera infantil (cremallera no incluida)", rate: HOURLY_TO_MINUTE_RATE(12) },
    ],
    "Vestidos de novia, invitadas y damas de honor": [
        { name: "Ajuste de cintura", rate: HOURLY_TO_MINUTE_RATE(30) },
        { name: "Ajuste de pecho", rate: HOURLY_TO_MINUTE_RATE(35) },
        { name: "Acortar largo", rate: HOURLY_TO_MINUTE_RATE(28) },
        { name: "Cambiar cremallera", rate: HOURLY_TO_MINUTE_RATE(40) },
        { name: "Añadir encaje o aplicaciones", rate: HOURLY_TO_MINUTE_RATE(30) },
        { name: "Reforzar costuras", rate: HOURLY_TO_MINUTE_RATE(25) },
        { name: "Ajuste de velos", rate: HOURLY_TO_MINUTE_RATE(30) },
        { name: "Planchado y preparación", rate: HOURLY_TO_MINUTE_RATE(40) },
    ],
    "Otros": [
        { name: "Coser roto", rate: HOURLY_TO_MINUTE_RATE(6) },
        { name: "Botones (unidad)", rate: HOURLY_TO_MINUTE_RATE(4) },
        { name: "Acortar tirantes de bikini", rate: HOURLY_TO_MINUTE_RATE(6) },
        { name: "Cremallera de cojín", rate: HOURLY_TO_MINUTE_RATE(15) },
        { name: "Bajo de cortinas (ancho 130 cm)", rate: HOURLY_TO_MINUTE_RATE(14) },
    ]
};
